/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controller;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import views.PanelCaja;
import views.PanelConfiguraciones;
import views.PanelCreditos;
import views.PanelFacturas;
import views.PanelInventario;
import views.PanelReportes;

/**
 *
 * @author jason
 */
public class FarmaciaController extends javax.swing.JFrame {
    private int width;
    private int height;
    /**
     * Creates new form FarmaciaController
     */
    public FarmaciaController() {
        initComponents();
        obtenerResolucion();
        this.setSize(new Dimension(width, height));
        JPanelBienvenida.setSize(91, height);
        Contenedor.setSize(width - 91, height);
        this.setLocationRelativeTo(this.JPanelBienvenida);
        Image icono = new ImageIcon(getClass().getResource("/inventarioIcon.png")).getImage();

        this.setIconImage(icono);

        PanelInventario inventario = new PanelInventario();
        inventario.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        inventario.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(inventario);
        Contenedor.revalidate();
        Contenedor.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBienvenida = new javax.swing.JPanel();
        LabelBtnInventario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelBtnFacturas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelBtnCerrarSesion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelBtnConfiguración = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelBtnCreditos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Inventario Farmacia Yeshua");
        setBackground(new java.awt.Color(204, 255, 255));
        setFont(new java.awt.Font("Nunito", 0, 18)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1280, 7202));
        setMinimumSize(new java.awt.Dimension(720, 576));
        setPreferredSize(new java.awt.Dimension(720, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelBienvenida.setBackground(new java.awt.Color(179, 226, 236));
        JPanelBienvenida.setPreferredSize(new java.awt.Dimension(91, 700));

        LabelBtnInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBtnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventario.png"))); // NOI18N
        LabelBtnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnInventarioMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Inventario");

        LabelBtnFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBtnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/factura.png"))); // NOI18N
        LabelBtnFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnFacturasMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Facturas");

        LabelBtnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelBtnCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cerrar-sesion-alt(1).png"))); // NOI18N
        LabelBtnCerrarSesion.setText("Salir");
        LabelBtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnCerrarSesionMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ajustes");

        labelBtnConfiguración.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnConfiguración.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configuraciones.png"))); // NOI18N
        labelBtnConfiguración.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBtnConfiguraciónMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reporte-de-negocios.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Reportes");

        labelBtnCreditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBtnCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/colateral.png"))); // NOI18N
        labelBtnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBtnCreditosMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Creditos");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cajero-automatico.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Caja");

        javax.swing.GroupLayout JPanelBienvenidaLayout = new javax.swing.GroupLayout(JPanelBienvenida);
        JPanelBienvenida.setLayout(JPanelBienvenidaLayout);
        JPanelBienvenidaLayout.setHorizontalGroup(
            JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                .addGroup(JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBtnConfiguración, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelBtnCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelBtnFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBtnInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelBienvenidaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                                .addComponent(labelBtnCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JPanelBienvenidaLayout.setVerticalGroup(
            JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                .addComponent(LabelBtnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelBtnFacturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(labelBtnCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBtnConfiguración, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelBtnCerrarSesion)
                .addGap(64, 64, 64))
        );

        getContentPane().add(JPanelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 700));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 0, 1270, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void obtenerResolucion(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        width = screenSize.width;
        height = screenSize.height;
    }
    
    private void LabelBtnFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnFacturasMouseClicked
        PanelFacturas pFacturas = new PanelFacturas();
        pFacturas.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        pFacturas.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(pFacturas);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_LabelBtnFacturasMouseClicked

    private void LabelBtnInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnInventarioMouseClicked
        PanelInventario inventario = new PanelInventario();
        inventario.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        inventario.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(inventario);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_LabelBtnInventarioMouseClicked

    private void LabelBtnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnCerrarSesionMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LabelBtnCerrarSesionMouseClicked

    private void labelBtnConfiguraciónMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBtnConfiguraciónMouseClicked
        PanelConfiguraciones configuracones = new PanelConfiguraciones();
        configuracones.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        configuracones.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(configuracones);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_labelBtnConfiguraciónMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        PanelReportes reportes = new PanelReportes();
        reportes.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        reportes.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(reportes);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void labelBtnCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBtnCreditosMouseClicked
        PanelCreditos pCreditos = new PanelCreditos();
        pCreditos.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        pCreditos.setLocation(0, 0);

        Contenedor.removeAll();
        Contenedor.add(pCreditos);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_labelBtnCreditosMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        PanelCaja pCaja = new PanelCaja();
        pCaja.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        pCaja.setLocation(0, 0);
        
        Contenedor.removeAll();
        Contenedor.add(pCaja);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel JPanelBienvenida;
    private javax.swing.JLabel LabelBtnCerrarSesion;
    private javax.swing.JLabel LabelBtnFacturas;
    private javax.swing.JLabel LabelBtnInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelBtnConfiguración;
    private javax.swing.JLabel labelBtnCreditos;
    // End of variables declaration//GEN-END:variables
}
