/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controller;

import Configurations.HibernateUtil;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import models.Producto;
import org.hibernate.Session;
import views.PanelClientes;
import views.PanelInventario;

/**
 *
 * @author jason
 */
public class FarmaciaController extends javax.swing.JFrame {

    /**
     * Creates new form FarmaciaController
     */
    public FarmaciaController() {
        initComponents();
        
        this.setLocationRelativeTo(this.JPanelBienvenida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelBienvenida = new javax.swing.JPanel();
        LabelBtnInventario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelBtnFacturas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelBtnClientes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelBtnCerrarSesion = new javax.swing.JLabel();
        LabelBtnVentas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Contenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(1280, 7202));
        setMinimumSize(new java.awt.Dimension(720, 576));
        setPreferredSize(new java.awt.Dimension(720, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelBienvenida.setBackground(new java.awt.Color(204, 204, 255));
        JPanelBienvenida.setPreferredSize(new java.awt.Dimension(91, 700));

        LabelBtnInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBtnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alt-de-inventario.png"))); // NOI18N
        LabelBtnInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnInventarioMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inventario");

        LabelBtnFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBtnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/archivo-factura-dolar.png"))); // NOI18N
        LabelBtnFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnFacturasMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Facturas");

        LabelBtnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atencion-al-cliente(1).png"))); // NOI18N
        LabelBtnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnClientesMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Clientes");

        LabelBtnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cerrar-sesion-alt(1).png"))); // NOI18N
        LabelBtnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnCerrarSesionMouseClicked(evt);
            }
        });

        LabelBtnVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/venta(1).png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ventas");

        javax.swing.GroupLayout JPanelBienvenidaLayout = new javax.swing.GroupLayout(JPanelBienvenida);
        JPanelBienvenida.setLayout(JPanelBienvenidaLayout);
        JPanelBienvenidaLayout.setHorizontalGroup(
            JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                .addGroup(JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelBienvenidaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelBtnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelBtnFacturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelBtnInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelBtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                                .addGroup(JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelBtnCerrarSesion)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );
        JPanelBienvenidaLayout.setVerticalGroup(
            JPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBienvenidaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(LabelBtnInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(LabelBtnFacturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelBtnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelBtnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelBtnCerrarSesion)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        getContentPane().add(JPanelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 700));

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 0, 1260, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelBtnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnClientesMouseClicked
        PanelClientes pClientes = new PanelClientes();
        pClientes.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        pClientes.setLocation(0, 0);
        
        Contenedor.removeAll();
        Contenedor.add(pClientes);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_LabelBtnClientesMouseClicked

    private void LabelBtnFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnFacturasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelBtnFacturasMouseClicked

    private void LabelBtnInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnInventarioMouseClicked
        PanelInventario inventario = new PanelInventario();
        inventario.setSize(Contenedor.getWidth(), Contenedor.getHeight());
        inventario.setLocation(0, 0);
        
        Contenedor.removeAll();
        Contenedor.add(inventario);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_LabelBtnInventarioMouseClicked

    private void LabelBtnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnCerrarSesionMouseClicked
        System.exit(0);
    }//GEN-LAST:event_LabelBtnCerrarSesionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JPanel JPanelBienvenida;
    private javax.swing.JLabel LabelBtnCerrarSesion;
    private javax.swing.JLabel LabelBtnClientes;
    private javax.swing.JLabel LabelBtnFacturas;
    private javax.swing.JLabel LabelBtnInventario;
    private javax.swing.JLabel LabelBtnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
