/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import models.CajaModels.Caja;
import models.Micelanea.Micelanea;
import models.Productos;
import models.ViewModels.VistaFacturas;
import models.ViewModels.VistaFacturasProductos;
import services.FacturasClienteServices;

/**
 *
 * @author jason
 */
public class PanelFacturas extends javax.swing.JPanel {

    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();

    /**
     * Creates new form PanelFacturas
     */
    public PanelFacturas() {
        initComponents();
        ObtenerFacturas();
    }

    private void ObtenerFacturas() {
        List<VistaFacturas> listaFactura = new FacturasClienteServices().obtenerVistaFactura();

        DefaultTableModel modelF = new DefaultTableModel();

        String[] columnas = {
            "Cliente Id",
            "Nombre CLiente",
            "Factura cliente Id",
            "Factura Id",
            "Venta Id",
            "Fecha",
            "Sub Total",
            "Total",
            "Tipo Pago",
            "Tipo Venta"

        };

        modelF.setColumnIdentifiers(columnas);

        for (VistaFacturas vf : listaFactura) {
            String[] renglon = {
                String.valueOf(vf.getCliente_id()),
                vf.getNombre_Cliente(),
                String.valueOf(vf.getFactura_ClienteId()),
                String.valueOf(vf.getFacturaId()),
                String.valueOf(vf.getVentaId()),
                vf.getFecha().toString(),
                String.valueOf(vf.getSubtotal()),
                String.valueOf(vf.getTotal()),
                vf.getTipo_pago(),
                vf.getTipoVenta()
            };

            modelF.addRow(renglon);
        }

        JtableFacturas.setModel(modelF);

        model.setColumnIdentifiers(new String[]{
            "Factura id", "Venta id", "Tipo de Venta", "Producto Id", "Nombre", "Laboratorio", "Cantidad",
            "Precio por unidad", "Sub total"
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogProductosFactura = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductosFactura = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnReemBolsoCompleto = new javax.swing.JButton();
        btnReembolsoParcial = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableFacturas = new javax.swing.JTable();
        txtBuscarFactura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarFactura = new javax.swing.JButton();
        btnQuitarFiltro = new javax.swing.JButton();
        btnVerFactura = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jTableProductosFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableProductosFactura);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Productos la factura seleccionada");

        btnReemBolsoCompleto.setText("Reembolso Completo");
        btnReemBolsoCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReemBolsoCompletoActionPerformed(evt);
            }
        });

        btnReembolsoParcial.setText("Reembolso Parcial");
        btnReembolsoParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReembolsoParcialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnReemBolsoCompleto)
                .addGap(18, 18, 18)
                .addComponent(btnReembolsoParcial)
                .addGap(0, 85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReemBolsoCompleto)
                            .addComponent(btnReembolsoParcial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogProductosFacturaLayout = new javax.swing.GroupLayout(jDialogProductosFactura.getContentPane());
        jDialogProductosFactura.getContentPane().setLayout(jDialogProductosFacturaLayout);
        jDialogProductosFacturaLayout.setHorizontalGroup(
            jDialogProductosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogProductosFacturaLayout.setVerticalGroup(
            jDialogProductosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setLayout(new java.awt.BorderLayout());

        JtableFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtableFacturas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");

        btnBuscarFactura.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscarFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscarFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarFactura.setText("Buscar");
        btnBuscarFactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnBuscarFactura.setBorderPainted(false);
        btnBuscarFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFacturaActionPerformed(evt);
            }
        });

        btnQuitarFiltro.setBackground(java.awt.Color.red);
        btnQuitarFiltro.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitarFiltro.setText("Quitar Filtro");
        btnQuitarFiltro.setToolTipText("");
        btnQuitarFiltro.setActionCommand("Quitar");
        btnQuitarFiltro.setBorderPainted(false);
        btnQuitarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarFiltroActionPerformed(evt);
            }
        });

        btnVerFactura.setText("Ver");
        btnVerFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFacturaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Panel de facturas Recientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVerFactura)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuitarFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuitarFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFacturaActionPerformed
        if (txtBuscarFactura.getText().isBlank()) {
            JOptionPane.showMessageDialog(jPanel1,
                    "Escriba un nombre para poder realizar una busqueda");
        } else {
            String clave = txtBuscarFactura.getText();

            List<VistaFacturas> listaFactura = new FacturasClienteServices().obtenerVistaFacturaByName(clave);

            DefaultTableModel model = new DefaultTableModel();

            String[] columnas = {
                "Cliente Id",
                "Nombre CLiente",
                "Factura cliente Id",
                "Factura Id",
                "Venta Id",
                "Fecha",
                "Sub Total",
                "Total",
                "Tipo Pago",
                "Tipo Venta"
            };

            model.setColumnIdentifiers(columnas);

            for (VistaFacturas vf : listaFactura) {
                String[] renglon = {
                    String.valueOf(vf.getCliente_id()),
                    vf.getNombre_Cliente(),
                    String.valueOf(vf.getFactura_ClienteId()),
                    String.valueOf(vf.getFacturaId()),
                    String.valueOf(vf.getVentaId()),
                    vf.getFecha().toString(),
                    String.valueOf(vf.getSubtotal()),
                    String.valueOf(vf.getTotal()),
                    vf.getTipo_pago(),
                    vf.getTipoVenta()
                };

                model.addRow(renglon);
            }

            JtableFacturas.setModel(model);
        }


    }//GEN-LAST:event_btnBuscarFacturaActionPerformed

    private void btnQuitarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarFiltroActionPerformed
        ObtenerFacturas();
        txtBuscarFactura.setText("");
    }//GEN-LAST:event_btnQuitarFiltroActionPerformed

    private void btnVerFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFacturaActionPerformed
        int fila = JtableFacturas.getSelectedRow();

        model.setRowCount(0);
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla");
        } else {
            int facturaId = Integer.parseInt((String) JtableFacturas.getValueAt(fila, 2));

            try {
                List<VistaFacturasProductos> listaFactura = new FacturasClienteServices().obtenerVistaFacturaByFactura(facturaId);

                if (!listaFactura.isEmpty()) {

                    for (VistaFacturasProductos vfp : listaFactura) {
                        String[] renglon = {
                            String.valueOf(vfp.getFactura_id()),
                            String.valueOf(vfp.getVentaId()),
                            vfp.getTipoVenta(),
                            String.valueOf(vfp.getProductoId()),
                            vfp.getNombre(),
                            vfp.getMarca(),
                            String.valueOf(vfp.getCantidad()),
                            String.valueOf(vfp.getPrecio()),
                            String.valueOf(vfp.getSubtotal())
                        };

                        model.addRow(renglon);
                    }

                    jTableProductosFactura.setModel(model);

                    jDialogProductosFactura.setVisible(true);
                    jDialogProductosFactura.setSize(720, 300);
                    jDialogProductosFactura.setLocationRelativeTo(this);

                } else {
                    JOptionPane.showMessageDialog(this, "Los registros de esta venta son miscelaneas");
                    
                    model2.setColumnIdentifiers(new String[]{
                        "Factura id", "Venta id", "Tipo de Venta", "Producto Id", "Nombre", "Cantidad",
                        "Precio por unidad", "Sub total"
                    });

                    List<Object[]> objetos = new FacturasClienteServices().obtenerVistaMicelaneaByFactura(facturaId);

                    if (!objetos.isEmpty()) {
                        for (Object[] o : objetos) {
                            String[] renglon = {
                                String.valueOf(o[0]),
                                String.valueOf(o[1]),
                                String.valueOf(o[2]),
                                String.valueOf(o[3]),
                                String.valueOf(o[4]),
                                String.valueOf(o[5]),
                                String.valueOf(o[6]),
                                String.valueOf(o[7])
                            };

                            model2.addRow(renglon);
                        }

                        jTableProductosFactura.setModel(model2);
                        jDialogProductosFactura.setVisible(true);
                        jDialogProductosFactura.setSize(720, 300);
                        jDialogProductosFactura.setLocationRelativeTo(this);
                    }
                }

            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnVerFacturaActionPerformed

    private void btnReemBolsoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReemBolsoCompletoActionPerformed
        try {
            if (jTableProductosFactura.getModel().getColumnCount() == 9) {
                Caja caja = PanelCaja.obtenerCaja();

                if (caja != null) {
                    List<Productos> productos = new ArrayList<>();
                    int ventaId = Integer.parseInt((String) jTableProductosFactura.getValueAt(0, 1));
                    for (int i = 0; i < jTableProductosFactura.getRowCount(); i++) {

                        int id_producto = Integer.parseInt((String) jTableProductosFactura.getValueAt(i, 3));

                        int cantidad = Integer.parseInt((String) jTableProductosFactura.getValueAt(i, 6));

                        productos.add(new Productos(id_producto, cantidad));
                    }

                    String message = new FacturasClienteServices().reembolsoCompleto(productos, ventaId, caja);
                    JOptionPane.showMessageDialog(this, message);

                    model.setRowCount(0);
                    jDialogProductosFactura.dispose();

                    ObtenerFacturas();
                } else {
                    JOptionPane.showMessageDialog(this, "Abra caja para registrar el movimiento del reembolso");
                }
            } else {
                Caja caja = PanelCaja.obtenerCaja();

                if (caja != null) {
                    List<Micelanea> productos = new ArrayList<>();
                    int ventaId = Integer.parseInt((String) jTableProductosFactura.getValueAt(0, 1));
                    for (int i = 0; i < jTableProductosFactura.getRowCount(); i++) {

                        int id_producto = Integer.parseInt((String) jTableProductosFactura.getValueAt(i, 3));

                        int cantidad = Integer.parseInt((String) jTableProductosFactura.getValueAt(i, 5));

                        productos.add(new Micelanea(id_producto, cantidad));
                    }

                    String message = new FacturasClienteServices().reembolsoCompletoMiscelanea(productos, ventaId, caja);
                    JOptionPane.showMessageDialog(this, message);

                    model.setRowCount(0);
                    jDialogProductosFactura.dispose();

                    ObtenerFacturas();
                } else {
                    JOptionPane.showMessageDialog(this, "Abra caja para registrar el movimiento del reembolso");
                }
            }

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnReemBolsoCompletoActionPerformed

    private void btnReembolsoParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReembolsoParcialActionPerformed
        int row = jTableProductosFactura.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla para hacer el reembolso");
        } else {
            try {
                if (jTableProductosFactura.getModel().getColumnCount() == 9) {
                    Caja caja = PanelCaja.obtenerCaja();

                    if (caja != null) {
                        int ventaId = Integer.parseInt((String) jTableProductosFactura.getValueAt(0, 1));

                        int id_producto = Integer.parseInt((String) jTableProductosFactura.getValueAt(row, 3));

                        int cantidad = Integer.parseInt((String) jTableProductosFactura.getValueAt(row, 6));

                        String message = new FacturasClienteServices().
                                reembolsoParcial(new Productos(id_producto, cantidad), ventaId, caja);

                        JOptionPane.showMessageDialog(this, message);
                        model.removeRow(row);
                        ObtenerFacturas();
                    } else {
                        JOptionPane.showMessageDialog(this, "Abra caja para registrar el movimiento del reembolso");
                    }
                } else {
                    Caja caja = PanelCaja.obtenerCaja();

                    if (caja != null) {
                        int ventaId = Integer.parseInt((String) jTableProductosFactura.getValueAt(0, 1));

                        int id_producto = Integer.parseInt((String) jTableProductosFactura.getValueAt(row, 3));

                        int cantidad = Integer.parseInt((String) jTableProductosFactura.getValueAt(row, 5));

                        String message = new FacturasClienteServices().
                                reembolsoParcialMiscelanea(new Micelanea(id_producto, cantidad), ventaId, caja);

                        JOptionPane.showMessageDialog(this, message);
                        model2.removeRow(row);
                        ObtenerFacturas();
                    } else {
                        JOptionPane.showMessageDialog(this, "Abra caja para registrar el movimiento del reembolso");
                    }
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnReembolsoParcialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableFacturas;
    private javax.swing.JButton btnBuscarFactura;
    private javax.swing.JButton btnQuitarFiltro;
    private javax.swing.JButton btnReemBolsoCompleto;
    private javax.swing.JButton btnReembolsoParcial;
    private javax.swing.JButton btnVerFactura;
    private javax.swing.JDialog jDialogProductosFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProductosFactura;
    private javax.swing.JTextField txtBuscarFactura;
    // End of variables declaration//GEN-END:variables
}
