/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import models.ViewModels.VentasMes;
import net.sf.jasperreports.engine.JRException;
import services.ReportesServices;
import services.VentasProductosServices;

/**
 *
 * @author jason
 */
public class PanelReportes extends javax.swing.JPanel {

    /**
     * Creates new form PanelReportes
     */
    public PanelReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReporteExistencias = new javax.swing.JButton();
        btnReporteVentas = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        btnReporteExistencias.setText("Existencia baja");
        btnReporteExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteExistenciasActionPerformed(evt);
            }
        });

        btnReporteVentas.setText("Reporte Ventas");
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnReporteExistencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnReporteVentas))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReporteExistencias)
                    .addComponent(btnReporteVentas))
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteExistenciasActionPerformed
        try {
            ReportesServices reporte = new ReportesServices();
            reporte.productosCantidadBaja();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnReporteExistenciasActionPerformed

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        
        
        Date fechaInicio = Date.valueOf(JOptionPane.showInputDialog(this, 
                "Ingresa la Fecha de Inicio para tu reporte", 
                "Fecha Inicial", JOptionPane.INFORMATION_MESSAGE));
        Date fechaFin = Date.valueOf(JOptionPane.showInputDialog(this, 
                "Ingrese la Fecha de final para tu reporte", 
                "Fecha Final", JOptionPane.INFORMATION_MESSAGE));

        try {
            List<VentasMes> ventas = new VentasProductosServices().obtenerVentaMes(fechaInicio, fechaFin);
            int Total_cantidad = ventas.stream().mapToInt(VentasMes::getTotalCantidad).sum();
            double total = ventas.stream().mapToDouble(VentasMes::getTotal_venta).sum();

            Map<String, Object> parametros = new HashMap<>();

            parametros.put("Total_cantidad", Total_cantidad);
            parametros.put("Total", total);

            ReportesServices reportesServices = new ReportesServices();

            reportesServices.ReporteVentasMes(parametros, ventas,
                    "/Reports/ReporteVentas.jrxml");

        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnReporteVentasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteExistencias;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
