/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.HeadlessException;
import java.awt.Rectangle;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.CajaModels.Caja;
import models.CajaModels.MovimientosCaja;
import models.CajaModels.Turno;
import models.Usuarios;
import services.Caja.CajaServices;
import services.Caja.MovimientoServices;
import services.Caja.TurnoServices;
import services.ReportesServices;
import services.UsuariosServices;

/**
 *
 * @author jason
 */
public class PanelCaja extends javax.swing.JPanel {

    private DefaultTableModel model;
    private static Turno sTurno;
    private static Caja sCaja;

    private double montoActual = 0.0;

    /**
     * Creates new form PanelCaja
     */
    public PanelCaja() {
        model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Id Movimiento", "Tipo de Movimiento", "Descripcion", "Monto", "Fecha"});

        initComponents();

        ObtenerVendedores();
        jTableMovimientos.setModel(model);
        ObtenerMovimientosCaja();
    }

    private void ObtenerMovimientosCaja() {
        model.setRowCount(0);
        if (sCaja != null) {

            List<MovimientosCaja> movimientos = new MovimientoServices().obtenerMovimientos(sCaja.getId_caja());

            if (movimientos != null) {
                for (MovimientosCaja m : movimientos) {
                    String[] renglon = {
                        String.valueOf(m.getId_movimiento()),
                        m.getTipoMovimiento(),
                        m.getDescripcion(),
                        String.valueOf(m.getMonto()),
                        String.valueOf(m.getFecha()).split("\\.")[0]
                    };

                    model.addRow(renglon);
                }

                BigDecimal dineroCaja = movimientos.stream().map(MovimientosCaja::getMonto).
                        reduce(sCaja.getMonto_Inicial(), BigDecimal::add);

                labelDineroCaja.setText("Total de Dinero en Caja: " + dineroCaja);

                jTableMovimientos.setModel(model);
            }
        }
    }

    private void ObtenerVendedores() {
        try {
            List<Usuarios> vendedores = new UsuariosServices().ObtenerVendedores();

            if (vendedores != null) {
                for (Usuarios v : vendedores) {
                    jComboVendedor.addItem(v);
                }
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public static Turno obtenerTurno() {
        return sTurno;
    }

    public static Caja obtenerCaja() {
        return sCaja;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogRetirarDinero = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtDineroCaja = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDineroRetiro = new javax.swing.JTextField();
        btnProcesarRetiro = new javax.swing.JButton();
        btnCancelarRetiro = new javax.swing.JButton();
        jComboBoxTipoRetiro = new javax.swing.JComboBox<>();
        jDialogTablaReporteCaja = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCajas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btbCrearReporteConId = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDialogDeposito = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        txtcantidadDeposito = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTipoDeposito = new javax.swing.JComboBox<>();
        jButtondeposito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMovimientos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAbrirCaja = new javax.swing.JButton();
        btnCerrarCaja = new javax.swing.JButton();
        btnAgregarDinero = new javax.swing.JButton();
        btnRetirarDinero = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboVendedor = new javax.swing.JComboBox<>();
        btnIniciarTurno = new javax.swing.JButton();
        btnCerrarTurno = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        labelDineroCaja = new javax.swing.JLabel();
        labelDineroInicial = new javax.swing.JLabel();
        btnReporteCaja = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Retirar dinero de Caja");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad de dinero en caja reportada");

        txtDineroCaja.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Catidad de dinero a retirar");

        btnProcesarRetiro.setText("Retirar Dinero");
        btnProcesarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarRetiroActionPerformed(evt);
            }
        });

        btnCancelarRetiro.setForeground(new java.awt.Color(255, 0, 0));
        btnCancelarRetiro.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDineroCaja)
                            .addComponent(jLabel5)
                            .addComponent(txtDineroRetiro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnProcesarRetiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelarRetiro)))
                        .addGap(33, 33, 33)
                        .addComponent(jComboBoxTipoRetiro, 0, 198, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDineroCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDineroRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcesarRetiro)
                    .addComponent(btnCancelarRetiro)
                    .addComponent(jComboBoxTipoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogRetirarDineroLayout = new javax.swing.GroupLayout(jDialogRetirarDinero.getContentPane());
        jDialogRetirarDinero.getContentPane().setLayout(jDialogRetirarDineroLayout);
        jDialogRetirarDineroLayout.setHorizontalGroup(
            jDialogRetirarDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogRetirarDineroLayout.setVerticalGroup(
            jDialogRetirarDineroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTableCajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCajas);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Selecciona una caja de la lista");

        btbCrearReporteConId.setText("Crear Reporte");
        btbCrearReporteConId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbCrearReporteConIdActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Cancelar reporte");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btbCrearReporteConId)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbCrearReporteConId)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jDialogTablaReporteCajaLayout = new javax.swing.GroupLayout(jDialogTablaReporteCaja.getContentPane());
        jDialogTablaReporteCaja.getContentPane().setLayout(jDialogTablaReporteCajaLayout);
        jDialogTablaReporteCajaLayout.setHorizontalGroup(
            jDialogTablaReporteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogTablaReporteCajaLayout.setVerticalGroup(
            jDialogTablaReporteCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Panel de Deposito");

        txtcantidadDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadDepositoActionPerformed(evt);
            }
        });

        jLabel8.setText("Cantidad de dinero a depositar");

        jLabel9.setText("Elija el banco al que deposita");

        jComboBoxTipoDeposito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposito Banpro", "Deposito Bac", "Venta de Recarga" }));

        jButtondeposito.setText("Realizar Deposito");
        jButtondeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondepositoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogDepositoLayout = new javax.swing.GroupLayout(jDialogDeposito.getContentPane());
        jDialogDeposito.getContentPane().setLayout(jDialogDepositoLayout);
        jDialogDepositoLayout.setHorizontalGroup(
            jDialogDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDepositoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(txtcantidadDeposito)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addComponent(jComboBoxTipoDeposito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtondeposito))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jDialogDepositoLayout.setVerticalGroup(
            jDialogDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDepositoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addComponent(txtcantidadDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxTipoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtondeposito)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTableMovimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableMovimientos);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido al panel de infomación de caja");

        btnAbrirCaja.setText("Abrir Caja");
        btnAbrirCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCajaActionPerformed(evt);
            }
        });

        btnCerrarCaja.setForeground(new java.awt.Color(255, 0, 0));
        btnCerrarCaja.setText("Cerrar Caja");
        btnCerrarCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCajaActionPerformed(evt);
            }
        });

        btnAgregarDinero.setForeground(new java.awt.Color(0, 204, 0));
        btnAgregarDinero.setText("Deposito Dinero");
        btnAgregarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDineroActionPerformed(evt);
            }
        });

        btnRetirarDinero.setForeground(new java.awt.Color(255, 0, 0));
        btnRetirarDinero.setText("Retirar Dinero");
        btnRetirarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarDineroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Establecer Turno");

        btnIniciarTurno.setText("Iniciar Turno");
        btnIniciarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarTurnoActionPerformed(evt);
            }
        });

        btnCerrarTurno.setText("Cerrar Turno");
        btnCerrarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarTurnoActionPerformed(evt);
            }
        });

        labelDineroCaja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDineroCaja.setText("Total de Dinero:");

        labelDineroInicial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelDineroInicial.setText("Dinero Inicial en Caja: ");

        btnReporteCaja.setText("Crear Reporte de caja");
        btnReporteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIniciarTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAgregarDinero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRetirarDinero)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCerrarTurno)
                                        .addGap(118, 118, 118)
                                        .addComponent(btnReporteCaja))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAbrirCaja)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCerrarCaja)
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDineroInicial)
                                            .addComponent(labelDineroCaja))))))
                        .addGap(0, 343, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciarTurno)
                    .addComponent(btnCerrarTurno)
                    .addComponent(btnReporteCaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(labelDineroInicial)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarDinero)
                        .addComponent(btnRetirarDinero))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAbrirCaja)
                        .addComponent(btnCerrarCaja)
                        .addComponent(labelDineroCaja)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarTurnoActionPerformed
        if (jComboVendedor.getSelectedIndex() == -1 || sCaja == null) {
            JOptionPane.showMessageDialog(this, "Abra Caja y Luego seleccione un vendedor de la lista");
        } else if (sTurno != null) {
            JOptionPane.showMessageDialog(this, "No se puede abrir un nuevo turno, ya esta uno en curso");
        } else {
            int id_vendedor = jComboVendedor.getItemAt(jComboVendedor.getSelectedIndex()).getId();
            Turno turno = new Turno();
            turno.setInicio(LocalDateTime.now());
            turno.setId_vendedor(id_vendedor);
            turno.setCaja(sCaja);

            try {
                String message = new TurnoServices().abrirTurno(turno);
                JOptionPane.showMessageDialog(this, message);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            sTurno = turno;
        }
    }//GEN-LAST:event_btnIniciarTurnoActionPerformed

    private void btnCerrarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarTurnoActionPerformed
        try {
            LocalDateTime fin = LocalDateTime.now();

            String message = new TurnoServices().cerrarTurno(sTurno.getId_turno(), fin);
            JOptionPane.showMessageDialog(this, message);
            TurnoServices service = new TurnoServices();
            service.obtenerVentasTurno(sTurno.getId_turno());
            sTurno = null;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCerrarTurnoActionPerformed

    private void btnAgregarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDineroActionPerformed
        jDialogDeposito.setBounds(new Rectangle(480, 280));
        jDialogDeposito.setLocationRelativeTo(this);
        jDialogDeposito.setVisible(true);

    }//GEN-LAST:event_btnAgregarDineroActionPerformed

    private void btnRetirarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarDineroActionPerformed
        if (sCaja != null) {
            jDialogRetirarDinero.setVisible(true);
            jDialogRetirarDinero.setBounds(new Rectangle(480, 300));
            jDialogRetirarDinero.setLocationRelativeTo(this);
            jComboBoxTipoRetiro.removeAllItems();
            jComboBoxTipoRetiro.addItem("Retiro Bac");
            jComboBoxTipoRetiro.addItem("Retiro Banpro");
            List<MovimientosCaja> movimientos = new MovimientoServices().obtenerMovimientos(sCaja.getId_caja());

            BigDecimal dinero = movimientos.stream().map(MovimientosCaja::getMonto).reduce(sCaja.getMonto_Inicial(), BigDecimal::add);
            txtDineroCaja.setText("" + dinero);

        } else {
            JOptionPane.showMessageDialog(this, "Caja aun no esta abierta por lo que no puede retirar dinero");
        }
    }//GEN-LAST:event_btnRetirarDineroActionPerformed

    private void btnAbrirCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCajaActionPerformed
        try {
            if (sCaja == null) {
                Caja caja = new Caja();
                caja.setApertura(LocalDateTime.now());
                BigDecimal montoInicial = BigDecimal.
                        valueOf(Double.
                                parseDouble(JOptionPane.showInputDialog("Ingrese el monto inicial de la caja")));
                caja.setMonto_Inicial(montoInicial);
                caja.setAbierta(true);

                String message = new CajaServices().abrirCaja(caja);

                sCaja = caja;

                BigDecimal dineroInicial = sCaja.getMonto_Inicial();

                labelDineroInicial.setText("Dinero Inicial en Caja: " + dineroInicial);

                JOptionPane.showMessageDialog(this, message);
            } else {
                JOptionPane.showMessageDialog(this, "No se puede abrir una nueva caja, estando una activa");
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El monto inicial no fue ingresado correctamente");
        }
    }//GEN-LAST:event_btnAbrirCajaActionPerformed

    private void btnCerrarCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCajaActionPerformed
        try {
            if (sTurno != null) {
                JOptionPane.showMessageDialog(this, "No se puede cerrar caja si el turno \nde un vendedor sigue activo");
            } else {
                LocalDateTime fCierre = LocalDateTime.now();

                Long id_caja = sCaja.getId_caja();

                String message = new CajaServices().cerrarCaja(id_caja, fCierre);
                JOptionPane.showMessageDialog(this, message);
                sCaja = null;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnCerrarCajaActionPerformed

    private void btnProcesarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarRetiroActionPerformed
        try {

            double montoRetiro = Double.parseDouble(txtDineroRetiro.getText());

            if (montoRetiro < Double.parseDouble((String) txtDineroCaja.getText())) {
                String message = new MovimientoServices()
                        .resgistrarMovimiento(sCaja, -montoRetiro, "RETIRO", jComboBoxTipoRetiro.getItemAt(jComboBoxTipoRetiro.getSelectedIndex()));
                JOptionPane.showMessageDialog(this, message);
            } else {
                JOptionPane.showMessageDialog(this, "El monto a retirar es mayor a la cantidad en caja");
            }

            ObtenerMovimientosCaja();
            jDialogRetirarDinero.dispose();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un numero correcto en el campo de retiro");
        }
    }//GEN-LAST:event_btnProcesarRetiroActionPerformed

    private void btnReporteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCajaActionPerformed
        jDialogTablaReporteCaja.setVisible(true);
        jDialogTablaReporteCaja.setBounds(new Rectangle(960, 580));
        jDialogTablaReporteCaja.setLocationRelativeTo(this);
        DefaultTableModel cajaTableModel = new DefaultTableModel();
        String[] columns = {"Id caja", "Fecha Apertura", "Fecha Cierre", "Monto Inicial", "Monto Final", "Abierta"};
        cajaTableModel.setColumnIdentifiers(columns);
        try {
            List<Caja> cajas = new CajaServices().obtenerCajas();

            if (cajas != null) {
                for (Caja c : cajas) {
                    String[] renglon = {
                        String.valueOf(c.getId_caja()),
                        String.valueOf(c.getApertura()).split("\\.")[0],
                        String.valueOf(c.getCierre()).split("\\.")[0],
                        String.valueOf(c.getMonto_Inicial()),
                        String.valueOf(c.getMonto_Final()),
                        String.valueOf(c.getAbierta())
                    };

                    cajaTableModel.addRow(renglon);

                }

                jTableCajas.setModel(cajaTableModel);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_btnReporteCajaActionPerformed

    private void btbCrearReporteConIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbCrearReporteConIdActionPerformed
        if (jTableCajas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecciones una caja de la tabla");
        } else {
            int row = jTableCajas.getSelectedRow();
            try {
                Long id_caja = Long.valueOf((String) jTableCajas.getValueAt(row, 0));

                ReportesServices reporte = new ReportesServices();
                reporte.reporteCaja(id_caja);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error de entrada: el id no es un numero!");
            }
        }
    }//GEN-LAST:event_btbCrearReporteConIdActionPerformed

    private void txtcantidadDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadDepositoActionPerformed

    private void jButtondepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondepositoActionPerformed
        try {
            if (sCaja != null) {
                double montoIngreso = Double.parseDouble(txtcantidadDeposito.getText());

                String descripcion = jComboBoxTipoDeposito.getItemAt(jComboBoxTipoDeposito.getSelectedIndex());

                String message = new MovimientoServices()
                        .resgistrarMovimiento(sCaja, montoIngreso, "INGRESO", descripcion);
                JOptionPane.showMessageDialog(this, message);
                ObtenerMovimientosCaja();
            } else {
                JOptionPane.showMessageDialog(this, "Abra una caja y un turno para realizar esta acción");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Asegurese de ingresar un numero de manera correcta: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtondepositoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbCrearReporteConId;
    private javax.swing.JButton btnAbrirCaja;
    private javax.swing.JButton btnAgregarDinero;
    private javax.swing.JButton btnCancelarRetiro;
    private javax.swing.JButton btnCerrarCaja;
    private javax.swing.JButton btnCerrarTurno;
    private javax.swing.JButton btnIniciarTurno;
    private javax.swing.JButton btnProcesarRetiro;
    private javax.swing.JButton btnReporteCaja;
    private javax.swing.JButton btnRetirarDinero;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtondeposito;
    private javax.swing.JComboBox<String> jComboBoxTipoDeposito;
    private javax.swing.JComboBox<String> jComboBoxTipoRetiro;
    private javax.swing.JComboBox<Usuarios> jComboVendedor;
    private javax.swing.JDialog jDialogDeposito;
    private javax.swing.JDialog jDialogRetirarDinero;
    private javax.swing.JDialog jDialogTablaReporteCaja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableCajas;
    private javax.swing.JTable jTableMovimientos;
    private javax.swing.JLabel labelDineroCaja;
    private javax.swing.JLabel labelDineroInicial;
    private javax.swing.JTextField txtDineroCaja;
    private javax.swing.JTextField txtDineroRetiro;
    private javax.swing.JTextField txtcantidadDeposito;
    // End of variables declaration//GEN-END:variables
}
