/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.sql.Date;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.CajaModels.Caja;
import models.CajaModels.Turno;
import models.ViewModels.VistaCredito;
import models.pagosCredito;
import org.hibernate.NonUniqueResultException;
import services.Caja.MovimientoServices;
import services.CreditoServices;
import services.PagoCreditosServices;

/**
 *
 * @author jason
 */
public class PanelCreditos extends javax.swing.JPanel {

    private final DefaultTableModel modelTabla = new DefaultTableModel();

    private final String[] columnas = {
        "Id Credito", "Id Cliente", "Nombre", "Telefono", "Dirección", "Id Factura",
        "Monto Total", "Saldo Pendiente", "Estado", "Interes", "Fecha inicial",
        "Fecha Vencimiento"
    };

    public PanelCreditos() {
        initComponents();

        modelTabla.setColumnIdentifiers(columnas);

        ObtenerDatosCreditos();

        txtFechaPagoCredito.setText(LocalDate.now().toString());

    }

    private void ObtenerDatosCreditos() {
        modelTabla.setRowCount(0);

        List<VistaCredito> creditos = new CreditoServices().obtenerCreditos();

        if (creditos != null) {
            for (VistaCredito c : creditos) {

                String[] renglon = {
                    String.valueOf(c.getId_credito()),
                    String.valueOf(c.getId_cliente()),
                    c.getNombre(),
                    c.getTelefono(),
                    c.getDireccion(),
                    String.valueOf(c.getId_factura()),
                    String.valueOf(c.getMonto_total()),
                    String.valueOf(c.getSaldo_pendiente()),
                    c.getEstado().toUpperCase(),
                    String.valueOf(c.getInteres()),
                    String.valueOf(c.getFecha_inicial()),
                    String.valueOf(c.getFecha_vencimiento())
                };

                modelTabla.addRow(renglon);
            }

            jTableCreditos.setModel(modelTabla);
        }
    }

    private void limpiarCamposCreditos() {
        txtIdClienteCredito.setText("");
        txtIdCredito.setText("");
        txtMontoPago.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdCredito = new javax.swing.JTextField();
        txtIdClienteCredito = new javax.swing.JTextField();
        txtMontoPago = new javax.swing.JTextField();
        txtFechaPagoCredito = new javax.swing.JTextField();
        btnSeleccionarCredito = new javax.swing.JButton();
        btbAbonarCredito = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCreditos = new javax.swing.JTable();
        btnReporteCreditos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtBuscarClienteCredito = new javax.swing.JTextField();
        btnBuscarClienteCredito = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnBorrarFiltroBuscar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtSaldoCredito = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Modulo de Creditos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Id credito");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Id Cliente");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Monto a pagar");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Fecha: ");

        txtIdCredito.setEditable(false);
        txtIdCredito.setEnabled(false);

        btnSeleccionarCredito.setText("Seleccionar");
        btnSeleccionarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCreditoActionPerformed(evt);
            }
        });

        btbAbonarCredito.setText("Abonar");
        btbAbonarCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAbonarCreditoActionPerformed(evt);
            }
        });

        jTableCreditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCreditos);

        btnReporteCreditos.setText("Reporte de Creditos");
        btnReporteCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteCreditosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Buscar Credito de:");

        btnBuscarClienteCredito.setText("Buscar");
        btnBuscarClienteCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteCreditoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre");

        btnBorrarFiltroBuscar.setForeground(new java.awt.Color(255, 0, 0));
        btnBorrarFiltroBuscar.setText("Eliminar Filtro");
        btnBorrarFiltroBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBorrarFiltroBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarFiltroBuscarActionPerformed(evt);
            }
        });

        jLabel8.setText("Saldo Credito");

        txtSaldoCredito.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarClienteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarClienteCredito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBorrarFiltroBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtIdCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btbAbonarCredito))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdClienteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSeleccionarCredito)
                                        .addGap(88, 88, 88)
                                        .addComponent(btnReporteCreditos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMontoPago, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel8)
                                            .addComponent(txtSaldoCredito))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFechaPagoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdClienteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaPagoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(txtSaldoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbAbonarCredito)
                    .addComponent(btnSeleccionarCredito)
                    .addComponent(btnReporteCreditos))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuscarClienteCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarClienteCredito)
                    .addComponent(btnBorrarFiltroBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validarCampos() {
        return txtIdCredito.getText().isBlank() || txtMontoPago.getText().isBlank() || txtFechaPagoCredito.getText().isBlank();
    }

    private void btbAbonarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAbonarCreditoActionPerformed

        try {
            Caja caja = PanelCaja.obtenerCaja();
            Turno turno = PanelCaja.obtenerTurno();

            if (validarCampos()) {
                throw new IllegalArgumentException("Los campos de: \nId Credito, \nMonto pago\nDeben de tener información");
            } else if (caja == null || turno == null) {
                JOptionPane.showMessageDialog(this, "No se puede realizar un pago de credito si no hay: \nun turno y una caja abierta");
            } else {
                int id_credito = Integer.parseInt((String) txtIdCredito.getText());
                Double monto_pago = Double.valueOf((String) txtMontoPago.getText());
                Date fecha_pago = Date.valueOf((String) txtFechaPagoCredito.getText());
                
                Double saldo = Double.valueOf((String) txtSaldoCredito.getText());
                
                if(monto_pago > saldo){
                    throw new IllegalArgumentException("El monto de pago no puede ser superior a el saldo pendiente");
                }

                String message = new PagoCreditosServices()
                        .efectuarPago(new pagosCredito(id_credito, fecha_pago, monto_pago, turno));
                JOptionPane.showMessageDialog(this, message);

                String respuesta = new MovimientoServices().resgistrarMovimiento(caja, monto_pago, "PAGO CREDITO", "Pago");
                System.out.println(respuesta);

                limpiarCamposCreditos();
                ObtenerDatosCreditos();
            }

        } catch (IllegalArgumentException | NonUniqueResultException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Asegurese de que haya un turno y una caja abiertos");
        }

    }//GEN-LAST:event_btbAbonarCreditoActionPerformed

    private void btnSeleccionarCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCreditoActionPerformed
        int row = this.jTableCreditos.getSelectedRow();
        String estado = (String) jTableCreditos.getValueAt(row, 8);
        if (row == -1) {
            JOptionPane.showConfirmDialog(this, "Seleccione un credito de la tabla");
        } else if (estado.equalsIgnoreCase("PAGADO")) {
            JOptionPane.showMessageDialog(this, "No puedes seleccionar este credito por que: \nYa esta pagado");
        } else {
            String id_credito = (String) jTableCreditos.getValueAt(row, 0);
            String id_cliente = (String) jTableCreditos.getValueAt(row, 1);
            String nombre_cliente = (String) jTableCreditos.getValueAt(row, 2);
            
            String saldo = (String) jTableCreditos.getValueAt(row, 7);

            txtIdClienteCredito.setText(id_cliente);
            txtIdCredito.setText(id_credito);
            txtNombreCliente.setText(nombre_cliente);
            txtSaldoCredito.setText(saldo);
        }
    }//GEN-LAST:event_btnSeleccionarCreditoActionPerformed


    private void btnBuscarClienteCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteCreditoActionPerformed
        modelTabla.setRowCount(0);

        String clave = txtBuscarClienteCredito.getText();

        List<VistaCredito> creditos = new CreditoServices().buscarCreditoByName(clave);

        if (creditos != null) {
            for (VistaCredito c : creditos) {

                String[] renglon = {
                    String.valueOf(c.getId_credito()),
                    String.valueOf(c.getId_cliente()),
                    c.getNombre(),
                    c.getTelefono(),
                    c.getDireccion(),
                    String.valueOf(c.getId_factura()),
                    String.valueOf(c.getMonto_total()),
                    String.valueOf(c.getSaldo_pendiente()),
                    c.getEstado(),
                    String.valueOf(c.getInteres()),
                    String.valueOf(c.getFecha_inicial()),
                    String.valueOf(c.getFecha_vencimiento())
                };

                modelTabla.addRow(renglon);
            }

            jTableCreditos.setModel(modelTabla);
        }
    }//GEN-LAST:event_btnBuscarClienteCreditoActionPerformed

    private void btnReporteCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteCreditosActionPerformed

    }//GEN-LAST:event_btnReporteCreditosActionPerformed

    private void btnBorrarFiltroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarFiltroBuscarActionPerformed
        ObtenerDatosCreditos();
        txtBuscarClienteCredito.setText("");
    }//GEN-LAST:event_btnBorrarFiltroBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAbonarCredito;
    private javax.swing.JButton btnBorrarFiltroBuscar;
    private javax.swing.JButton btnBuscarClienteCredito;
    private javax.swing.JButton btnReporteCreditos;
    private javax.swing.JButton btnSeleccionarCredito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCreditos;
    private javax.swing.JTextField txtBuscarClienteCredito;
    private javax.swing.JTextField txtFechaPagoCredito;
    private javax.swing.JTextField txtIdClienteCredito;
    private javax.swing.JTextField txtIdCredito;
    private javax.swing.JTextField txtMontoPago;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtSaldoCredito;
    // End of variables declaration//GEN-END:variables
}
