/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.HeadlessException;
import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Categoria;
import models.Producto;
import services.CategoriaServices;
import services.ProductoService;

/**
 *
 * @author jason
 */
public class PanelInventario extends javax.swing.JPanel {

    private DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form PanelInventario
     */
    public PanelInventario() {
        initComponents();
        obtenerDatos();

        tableModel = (DefaultTableModel) JTableProductos.getModel();
    }

    private void obtenerDatos() {
        Map<Integer, String> categorias = obtenerCategorias();

        List<Producto> productos = new ProductoService().obtenerProductos();
        DefaultTableModel model = new DefaultTableModel();
        String[] Columnas = {"Id", "Nombre", "Indicaciones", "Marca",
            "Categoria", "Precio", "Cantidad", "Fecha_caducidad"};

        model.setColumnIdentifiers(Columnas);

        for (Producto p : productos) {
            String nombreCategoria = categorias.get(p.getCategoria_id());
            String[] renglon = {
                String.valueOf(p.getId()),
                p.getNombre(),
                p.getIndicaciones(),
                p.getMarca(),
                nombreCategoria,
                String.valueOf(p.getPrecio()),
                String.valueOf(p.getCantidad()),
                p.getFecha_vencimiento().toString()
            };

            model.addRow(renglon);
        }

        jlabelTotal_Inventario.setText("Total de Productos en inventario: "
                + obtenerTotalProductos() + " Productos");

        JTableProductos.setModel(model);

    }

    private Map<Integer, String> obtenerCategorias() {
        try {
            List<Categoria> categorias = new CategoriaServices().obtenerCategorias();
            Map<Integer, String> categoriasMap = new HashMap<>();

            for (Categoria c : categorias) {
                jComboCategoriaProducto.addItem(new Categoria(c.getId(),
                        c.getNombre_categoria()));

                int id = c.getId();
                String nombre = c.getNombre_categoria();
                categoriasMap.put(id, nombre);
            }
            return categoriasMap;
        } catch (Exception e) {
            throw new RuntimeException("Error al ejecutar la consulta");
        }
    }

    private int obtenerTotalProductos() {
        return new ProductoService().obtenerCantidadProductosTotal();
    }

    private void LimpiarCampos() {
        txtIdProducto.setText("");
        txtNombreProducto.setText("");
        txtIndicacionesProducto.setText("");
        txtMarcaProducto.setText("");
        txtPrecioProducto.setText("");
        txtCantidadProducto.setText("");
        txtFecha_Vencimiento_Producto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogProductos = new javax.swing.JDialog();
        PanelCrearProducto = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtIndicacionesProducto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMarcaProducto = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboCategoriaProducto = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtFecha_Vencimiento_Producto = new javax.swing.JTextField();
        LabelBtnGuardarProducto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jPanelInventario = new javax.swing.JPanel();
        jlabelTotal_Inventario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableProductos = new javax.swing.JTable();
        btnCrearProductos = new javax.swing.JButton();
        btnEliminarProductos = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();

        jDialogProductos.setBounds(new java.awt.Rectangle(0, 0, 530, 400));
        jDialogProductos.setPreferredSize(new java.awt.Dimension(500, 400));
        jDialogProductos.setResizable(false);

        PanelCrearProducto.setPreferredSize(new java.awt.Dimension(480, 350));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Nombre");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Indicaciones");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Marca");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Categoria");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Precio");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Cantidad");

        txtCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Fecha de Vencimiento");

        LabelBtnGuardarProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LabelBtnGuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disco.png"))); // NOI18N
        LabelBtnGuardarProducto.setText("Guardar Producto");
        LabelBtnGuardarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBtnGuardarProductoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Id");

        txtIdProducto.setEnabled(false);

        javax.swing.GroupLayout PanelCrearProductoLayout = new javax.swing.GroupLayout(PanelCrearProducto);
        PanelCrearProducto.setLayout(PanelCrearProductoLayout);
        PanelCrearProductoLayout.setHorizontalGroup(
            PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCrearProductoLayout.createSequentialGroup()
                                .addComponent(txtIndicacionesProducto)
                                .addGap(18, 18, 18)
                                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txtMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFecha_Vencimiento_Producto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                        .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel20))
                            .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                                        .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LabelBtnGuardarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jComboCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                        .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCrearProductoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jLabel19))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelCrearProductoLayout.setVerticalGroup(
            PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCrearProductoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIndicacionesProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel22))
                .addGap(6, 6, 6)
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha_Vencimiento_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCrearProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelBtnGuardarProducto))
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout jDialogProductosLayout = new javax.swing.GroupLayout(jDialogProductos.getContentPane());
        jDialogProductos.getContentPane().setLayout(jDialogProductosLayout);
        jDialogProductosLayout.setHorizontalGroup(
            jDialogProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jDialogProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE))
        );
        jDialogProductosLayout.setVerticalGroup(
            jDialogProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jDialogProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelCrearProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(762, 501));
        setLayout(new java.awt.BorderLayout());

        jPanelInventario.setBackground(new java.awt.Color(255, 255, 255));

        jlabelTotal_Inventario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlabelTotal_Inventario.setText("Total en inventario:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia(2).png"))); // NOI18N
        jLabel1.setText("Inventario Farmacia Jeshua");

        JTableProductos.setBackground(new java.awt.Color(204, 204, 255));
        JTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTableProductos.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(JTableProductos);

        btnCrearProductos.setText("Crear");
        btnCrearProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearProductosMouseClicked(evt);
            }
        });

        btnEliminarProductos.setText("Eliminar");

        btnEditarProducto.setText("Editar");
        btnEditarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarProductoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelInventarioLayout = new javax.swing.GroupLayout(jPanelInventario);
        jPanelInventario.setLayout(jPanelInventarioLayout);
        jPanelInventarioLayout.setHorizontalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelInventarioLayout.createSequentialGroup()
                        .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jlabelTotal_Inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                                .addComponent(btnCrearProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditarProducto))
                            .addComponent(btnEliminarProductos))
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        jPanelInventarioLayout.setVerticalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrearProductos)
                        .addComponent(btnEditarProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelTotal_Inventario)
                    .addComponent(btnEliminarProductos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanelInventario, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoActionPerformed

    private void btnCrearProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearProductosMouseClicked
        LimpiarCampos();
        jDialogProductos.setVisible(true);
        jDialogProductos.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnCrearProductosMouseClicked

    private void LabelBtnGuardarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBtnGuardarProductoMouseClicked

        String nombre = txtNombreProducto.getText();
        String indicaciones = txtIndicacionesProducto.getText();
        String marca = txtMarcaProducto.getText();
        int categoria_id = jComboCategoriaProducto.
                getItemAt(jComboCategoriaProducto.getSelectedIndex()).getId();
        double precio = Double.parseDouble(txtPrecioProducto.getText());
        int cantidad = Integer.parseInt(txtCantidadProducto.getText());
        Date fecha_vencimiento = Date.valueOf(txtFecha_Vencimiento_Producto.getText());

        //Construccion del objeto
        Producto producto = new Producto(nombre,
                indicaciones, marca, categoria_id,
                precio, cantidad, fecha_vencimiento);

        try {
            String response = new ProductoService().crearProducto(producto);
            JOptionPane.showMessageDialog(PanelCrearProducto, response);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(PanelCrearProducto, e.getMessage());
        }

        LimpiarCampos();
        obtenerDatos();
    }//GEN-LAST:event_LabelBtnGuardarProductoMouseClicked

    private void btnEditarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarProductoMouseClicked
        int fila = this.JTableProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(PanelCrearProducto, "Seleccione un registro de la tabla");
        } else {
            try {
                jDialogProductos.setVisible(true);
                jDialogProductos.setLocationRelativeTo(this);
                int id = Integer.parseInt((String) this.JTableProductos.
                        getValueAt(fila, 0).toString());

                String nombre = (String) this.JTableProductos.getValueAt(fila, 1);
                String indicaciones = (String) this.JTableProductos.getValueAt(fila, 2);
                String marca = (String) this.JTableProductos.getValueAt(fila, 3);
                double precio = Double.parseDouble((String) this.JTableProductos.
                        getValueAt(fila, 5).toString());

                int cantidad = Integer.parseInt((String) this.JTableProductos.
                        getValueAt(fila, 6).toString());
                Date fecha = Date.valueOf((String) this.JTableProductos.
                        getValueAt(fila, 7).toString().split(" ")[0]);

                txtIdProducto.setText("" + id);
                txtNombreProducto.setText(nombre);
                txtIndicacionesProducto.setText(indicaciones);
                txtMarcaProducto.setText(marca);
                txtPrecioProducto.setText(String.valueOf(precio));
                txtCantidadProducto.setText(String.valueOf(cantidad));
                txtFecha_Vencimiento_Producto.setText(fecha.toString());

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(PanelCrearProducto, "error al intentar editar el producto: " + e.getMessage());
            }
        }


    }//GEN-LAST:event_btnEditarProductoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableProductos;
    private javax.swing.JLabel LabelBtnGuardarProducto;
    private javax.swing.JPanel PanelCrearProducto;
    private javax.swing.JButton btnCrearProductos;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEliminarProductos;
    private javax.swing.JComboBox<Categoria> jComboCategoriaProducto;
    private javax.swing.JDialog jDialogProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanelInventario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabelTotal_Inventario;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtFecha_Vencimiento_Producto;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtIndicacionesProducto;
    private javax.swing.JTextField txtMarcaProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
